### ISSUE TITLE
Implement "say" and "think" primitives

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-vm#307]
Depends on https://github.com/LLK/scratch-render/issues/18 and https://github.com/LLK/scratch-vm/issues/287 (ideally).

**Comment by thisandagain** [comment]
Resolved in https://github.com/LLK/scratch-vm/pull/691

**Comment by seyna** [comment]
Sorry guys, probably I'm wrong but I'm not sure, but where are the say/think blocks? 

In official link [http://llk.github.io/scratch-vm/](http://llk.github.io/scratch-vm/) I can't find them.

I tried to download and build myself, but also in vain. If there anyone could help? Thank you very much!

**Comment by Kenny2github** [comment]
@seyna the say/think blocks are not in the master branch yet, try the link https://llk.github.io/scratch-vm/develop

**Comment by mrjacobbloom** [comment]
That link is broken but they're working here: https://llk.github.io/scratch-gui/develop/

**Comment by seyna** [comment]
@Kenny2github I've downloaded the repository and build one using develop branch, however I still can't see say/think blocks.

@mrjacobbloom thank you for sharing the link, it does render blocks correctly, however I also need runtime which is provided by scratch-vm.
